# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BattleRub' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BattleRub

end

target 'cocos2d' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cocos2d

end

target 'ext_clipper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ext_clipper

end

target 'ext_convertUTF' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ext_convertUTF

end

target 'ext_edtaa3func' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ext_edtaa3func

end

target 'ext_md5' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ext_md5

end

target 'ext_poly2tri' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ext_poly2tri

end

target 'ext_recast' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ext_recast

end

target 'ext_tinyxml2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ext_tinyxml2

end

target 'ext_unzip' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ext_unzip

end

target 'ext_xxhash' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ext_xxhash

end

target 'ext_xxtea' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ext_xxtea

end

target 'external' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for external

end
